import type {
  PregnancyProfile,
  WeightLog,
  FoodEntry,
  SleepLog,
  SymptomLog,
  JournalEntry,
  KickLog,
  KegelLog,
  FeedingLog,
  DiaperLog,
  TummyTimeLog,
  BabyGrowthLog,
  MilestoneLog,
  Contraction,
} from '@nestly/shared';

const STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; color: #475569; background: #fff; }
  .header { background: rgb(190, 24, 93); padding: 24px 20px; color: #fff; }
  .header h1 { font-size: 28px; font-family: Georgia, serif; margin-bottom: 2px; }
  .header .subtitle { font-size: 8px; letter-spacing: 2px; text-transform: uppercase; opacity: 0.9; }
  .header .date { font-size: 11px; margin-top: 6px; opacity: 0.85; }
  .profile-card { background: #fff1f2; border-radius: 12px; padding: 14px 18px; margin: 16px 20px; }
  .profile-card .name { font-size: 14px; font-weight: 700; color: rgb(190, 24, 93); font-family: Georgia, serif; }
  .profile-card .detail { font-size: 11px; color: #475569; margin-top: 3px; }
  .section-title { font-size: 16px; font-weight: 700; color: rgb(190, 24, 93); font-family: Georgia, serif; margin: 20px 20px 8px; }
  .section-subtitle { font-size: 11px; color: #475569; margin: 0 20px 12px; }
  .stat-grid { display: flex; gap: 12px; margin: 0 20px 16px; }
  .stat-box { flex: 1; background: #fff1f2; border-radius: 12px; padding: 14px; }
  .stat-box .label { font-size: 8px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: rgb(236, 72, 153); margin-bottom: 8px; }
  .stat-box .row { font-size: 11px; color: #475569; margin-bottom: 4px; }
  .card { background: #fff1f2; border-radius: 12px; padding: 14px 18px; margin: 0 20px 12px; page-break-inside: avoid; }
  .card .card-title { font-size: 12px; font-weight: 700; color: rgb(236, 72, 153); margin-bottom: 6px; }
  .card .card-text { font-size: 11px; color: #475569; line-height: 1.5; }
  .footer { background: rgb(190, 24, 93); padding: 16px; text-align: center; color: #fff; font-size: 10px; font-weight: 700; margin-top: 24px; }
  .privacy { font-size: 8px; color: #94a3b8; text-align: center; margin: 8px 20px; }
  table { width: calc(100% - 40px); margin: 0 20px 16px; border-collapse: collapse; }
  th { background: #fff1f2; font-size: 9px; font-weight: 700; color: rgb(190, 24, 93); text-transform: uppercase; letter-spacing: 0.5px; padding: 8px 10px; text-align: left; }
  td { font-size: 11px; color: #475569; padding: 7px 10px; border-bottom: 1px solid #fce7f3; }
  tr:last-child td { border-bottom: none; }
`;

function wrap(title: string, body: string): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${STYLES}</style></head>
<body>${body}
<div class="footer">${title}</div>
<div class="privacy">Generated by Nestly. Your data stays on your device.</div>
</body></html>`;
}

function fmtDate(date: Date): string {
  return date.toLocaleDateString('en-GB', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).toUpperCase();
}

function filterByDay<T extends { timestamp: number }>(logs: T[], date: Date): T[] {
  const start = new Date(date).setHours(0, 0, 0, 0);
  const end = new Date(date).setHours(23, 59, 59, 999);
  return logs.filter((l) => l.timestamp >= start && l.timestamp <= end);
}

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// --- 1. Pregnancy Daily ---

export function buildPregnancyDailyHtml(params: {
  profile: PregnancyProfile;
  date: Date;
  weightLogs: WeightLog[];
  entries: FoodEntry[];
  sleepLogs: SleepLog[];
  symptoms: SymptomLog[];
  journalEntries: JournalEntry[];
  kickLogs: KickLog[];
  kegelLogs: KegelLog[];
}): string {
  const { profile, date } = params;
  const dayWeight = filterByDay(params.weightLogs, date);
  const dayFood = filterByDay(params.entries, date);
  const daySleep = params.sleepLogs.filter(
    (l) => !l.babyId && l.timestamp >= new Date(date).setHours(0, 0, 0, 0) && l.timestamp <= new Date(date).setHours(23, 59, 59, 999),
  );
  const daySymptoms = filterByDay(params.symptoms, date);
  const dayJournal = filterByDay(params.journalEntries, date);
  const dayKicks = filterByDay(params.kickLogs, date);
  const dayKegels = filterByDay(params.kegelLogs, date);

  const parentName = profile.userName || 'Parent';
  const babyNames = (profile.babies || []).map((b) => b.name || 'Baby').join(', ');
  const pregnancyType = profile.pregnancyType.charAt(0).toUpperCase() + profile.pregnancyType.slice(1);

  const nutrition = dayFood.reduce(
    (acc, f) => ({ c: acc.c + (f.calories || 0), p: acc.p + (f.protein || 0), i: acc.i + (f.iron || 0) }),
    { c: 0, p: 0, i: 0 },
  );

  const sleepHrs = daySleep.length > 0
    ? daySleep.reduce((a, s) => a + (new Date(s.endTime).getTime() - new Date(s.startTime).getTime()) / 3600000, 0).toFixed(1)
    : null;

  const kickTotal = dayKicks.reduce((a, k) => a + k.count, 0);

  const body = `
<div class="header">
  <h1>Nestly</h1>
  <div class="subtitle">YOUR PREGNANCY COMPANION</div>
  <div class="date">${fmtDate(date)}</div>
</div>
<div class="profile-card">
  <div class="name">${escHtml(parentName)}</div>
  <div class="detail">${escHtml(pregnancyType)} Journey: ${escHtml(babyNames)}</div>
</div>
<div class="section-title">Daily Pregnancy Report</div>
<div class="section-subtitle">A dedicated summary of your pregnancy well-being.</div>
<div class="stat-grid">
  <div class="stat-box">
    <div class="label">Vital Stats</div>
    <div class="row">Weight: ${dayWeight.length > 0 ? dayWeight[0].weight + ' kg' : '---'}</div>
    <div class="row">Sleep: ${sleepHrs ? sleepHrs + ' hrs' : '---'}</div>
  </div>
  <div class="stat-box">
    <div class="label">Pregnancy Tracking</div>
    <div class="row">Kick Count: ${kickTotal || '---'}</div>
    <div class="row">Kegel Sessions: ${dayKegels.length}</div>
    <div class="row">Symptoms Logged: ${daySymptoms.length}</div>
  </div>
</div>
<div class="card">
  <div class="card-title">Nutrition Summary</div>
  <div class="card-text">Calories: ${nutrition.c} kcal | Protein: ${nutrition.p}g | Iron: ${nutrition.i}mg</div>
</div>
${dayJournal.length > 0 ? `<div class="card"><div class="card-title">Daily Reflections</div>${dayJournal.map((j) => `<div class="card-text">${escHtml(j.content)}</div>`).join('')}</div>` : ''}`;

  return wrap('YOU ARE DOING AMAZING.', body);
}

// --- 2. Newborn Daily ---

export function buildNewbornDailyHtml(params: {
  profile: PregnancyProfile;
  date: Date;
  feedingLogs: FeedingLog[];
  diaperLogs: DiaperLog[];
  sleepLogs: SleepLog[];
  tummyTimeLogs: TummyTimeLog[];
  babyGrowthLogs: BabyGrowthLog[];
  journalEntries: JournalEntry[];
}): string {
  const { profile, date } = params;
  const dayFeedings = filterByDay(params.feedingLogs, date);
  const dayDiapers = filterByDay(params.diaperLogs, date);
  const daySleep = params.sleepLogs.filter(
    (l) => l.babyId && l.timestamp >= new Date(date).setHours(0, 0, 0, 0) && l.timestamp <= new Date(date).setHours(23, 59, 59, 999),
  );
  const dayTummy = filterByDay(params.tummyTimeLogs, date);
  const dayGrowth = filterByDay(params.babyGrowthLogs, date);
  const dayJournal = filterByDay(params.journalEntries, date);

  const parentName = profile.userName || 'Parent';
  const babyNames = (profile.babies || []).map((b) => b.name || 'Baby').join(', ');

  const totalMilk = dayFeedings.reduce((a, f) => a + (f.amount || 0), 0);
  const totalSleepHrs = daySleep.reduce((a, s) => {
    const ms = new Date(s.endTime).getTime() - new Date(s.startTime).getTime();
    return a + ms / 3600000;
  }, 0);
  const totalTummyMin = dayTummy.reduce((a, t) => a + (t.duration || 0), 0) / 60;
  const wetCount = dayDiapers.filter((d) => d.type === 'wet' || d.type === 'mixed').length;
  const dirtyCount = dayDiapers.filter((d) => d.type === 'dirty' || d.type === 'mixed').length;

  const body = `
<div class="header">
  <h1>Nestly</h1>
  <div class="subtitle">YOUR NEWBORN COMPANION</div>
  <div class="date">${fmtDate(date)}</div>
</div>
<div class="profile-card">
  <div class="name">Parent: ${escHtml(parentName)}</div>
  <div class="detail">Babies: ${escHtml(babyNames)}</div>
</div>
<div class="section-title">Daily Newborn Report</div>
<div class="section-subtitle">A snapshot of your baby's day.</div>
<div class="stat-grid">
  <div class="stat-box">
    <div class="label">Feeding & Sleep</div>
    <div class="row">Total Milk: ${totalMilk} ml</div>
    <div class="row">Feedings: ${dayFeedings.length}</div>
    <div class="row">Sleep: ${totalSleepHrs.toFixed(1)} hrs</div>
  </div>
  <div class="stat-box">
    <div class="label">Activity & Care</div>
    <div class="row">Diapers: ${dayDiapers.length} (${wetCount} wet, ${dirtyCount} dirty)</div>
    <div class="row">Tummy Time: ${totalTummyMin.toFixed(0)} min</div>
    <div class="row">Growth Logs: ${dayGrowth.length}</div>
  </div>
</div>
${dayGrowth.length > 0 ? `<div class="card"><div class="card-title">Latest Growth</div>${dayGrowth.map((g) => `<div class="card-text">Weight: ${g.weight} kg | Height: ${g.height} cm${g.headCircumference ? ' | Head: ' + g.headCircumference + ' cm' : ''}</div>`).join('')}</div>` : ''}
${dayJournal.length > 0 ? `<div class="card"><div class="card-title">Parental Reflections</div>${dayJournal.map((j) => `<div class="card-text">${escHtml(j.content)}</div>`).join('')}</div>` : ''}`;

  return wrap('YOU ARE DOING AMAZING.', body);
}

// --- 3. Labor Summary ---

export function buildLaborSummaryHtml(params: {
  profile: PregnancyProfile;
  date: Date;
  contractions: Contraction[];
}): string {
  const { profile, date, contractions } = params;
  const parentName = profile.userName || 'Parent';

  // Filter contractions to selected day by startTime
  const dayStart = new Date(date).setHours(0, 0, 0, 0);
  const dayEnd = new Date(date).setHours(23, 59, 59, 999);
  const dayContractions = contractions.filter((c) => c.startTime >= dayStart && c.startTime <= dayEnd);

  const sorted = [...dayContractions].sort((a, b) => a.startTime - b.startTime);

  const rows = sorted
    .map((c) => {
      const start = new Date(c.startTime).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      const end = c.endTime ? new Date(c.endTime).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '---';
      const dur = c.duration != null ? c.duration + 's' : '---';
      const interval = c.interval != null ? (c.interval / 60).toFixed(1) + ' min' : '---';
      return `<tr><td>${start}</td><td>${end}</td><td>${dur}</td><td>${interval}</td></tr>`;
    })
    .join('');

  const body = `
<div class="header">
  <h1>Nestly</h1>
  <div class="subtitle">CONTRACTION TRACKER</div>
  <div class="date">${fmtDate(date)}</div>
</div>
<div class="profile-card">
  <div class="name">${escHtml(parentName)}</div>
  <div class="detail">Labor Summary - ${dayContractions.length} contraction(s) recorded</div>
</div>
<div class="section-title">Contraction History</div>
<table>
  <thead><tr><th>Start</th><th>End</th><th>Duration</th><th>Interval</th></tr></thead>
  <tbody>${rows || '<tr><td colspan="4" style="text-align:center;">No contractions recorded</td></tr>'}</tbody>
</table>`;

  return wrap('LABOR SUMMARY', body);
}

// --- 4. Full Pregnancy Archive ---

export function buildFullPregnancyArchiveHtml(params: {
  profile: PregnancyProfile;
  kickLogs: KickLog[];
  weightLogs: WeightLog[];
  symptoms: SymptomLog[];
  kegelLogs: KegelLog[];
}): string {
  const { profile, kickLogs, weightLogs, symptoms, kegelLogs } = params;
  const parentName = profile.userName || 'Parent';
  const babyNames = (profile.babies || []).map((b) => b.name || 'Baby').join(', ');
  const pregnancyType = profile.pregnancyType.charAt(0).toUpperCase() + profile.pregnancyType.slice(1);

  const totalKicks = kickLogs.reduce((a, k) => a + k.count, 0);
  const totalKegelSec = kegelLogs.reduce((a, k) => a + k.duration, 0);

  const babiesHtml = (profile.babies || [])
    .map((b) => `<div class="card-text">${escHtml(b.name || 'Baby')} - ${escHtml(b.gender)}</div>`)
    .join('');

  const body = `
<div class="header">
  <h1>Nestly</h1>
  <div class="subtitle">A COMPLETE RECORD OF YOUR PREGNANCY JOURNEY</div>
  <div class="date">Pregnancy Archive</div>
</div>
<div class="profile-card">
  <div class="name">${escHtml(parentName)}</div>
  <div class="detail">${escHtml(pregnancyType)} | Due: ${escHtml(profile.dueDate)} | Babies: ${escHtml(babyNames)}</div>
</div>
${babiesHtml ? `<div class="card"><div class="card-title">The Babies</div>${babiesHtml}</div>` : ''}
<div class="section-title">Pregnancy Statistics</div>
<div class="stat-grid">
  <div class="stat-box">
    <div class="label">Activity</div>
    <div class="row">Total Kicks: ${totalKicks}</div>
    <div class="row">Kegel Time: ${Math.round(totalKegelSec / 60)} min</div>
  </div>
  <div class="stat-box">
    <div class="label">Records</div>
    <div class="row">Weight Entries: ${weightLogs.length}</div>
    <div class="row">Symptoms Logged: ${symptoms.length}</div>
  </div>
</div>`;

  return wrap('YOUR PREGNANCY JOURNEY - ARCHIVED BY NESTLY', body);
}

// --- 5. Full Newborn Archive ---

export function buildFullNewbornArchiveHtml(params: {
  profile: PregnancyProfile;
  feedingLogs: FeedingLog[];
  milestones: MilestoneLog[];
  diaperLogs: DiaperLog[];
  tummyTimeLogs: TummyTimeLog[];
}): string {
  const { profile, feedingLogs, milestones, diaperLogs, tummyTimeLogs } = params;
  const parentName = profile.userName || 'Parent';

  const babiesHtml = (profile.babies || [])
    .map((b) => {
      const parts = [escHtml(b.name || 'Baby'), escHtml(b.gender)];
      if (b.birthDate) parts.push('Born: ' + escHtml(b.birthDate));
      if (b.birthWeight) parts.push(b.birthWeight + ' kg');
      return `<div class="card-text">${parts.join(' - ')}</div>`;
    })
    .join('');

  const totalTummyMin = tummyTimeLogs.reduce((a, t) => a + (t.duration || 0), 0) / 60;

  const milestoneRows = [...milestones]
    .sort((a, b) => a.timestamp - b.timestamp)
    .slice(0, 50)
    .map((m) => `<tr><td>${escHtml(m.date)}</td><td>${escHtml(m.title)}</td><td>${m.notes ? escHtml(m.notes) : ''}</td></tr>`)
    .join('');

  const body = `
<div class="header">
  <h1>Nestly</h1>
  <div class="subtitle">A COMPLETE RECORD OF YOUR BABY'S FIRST DAYS</div>
  <div class="date">Newborn Archive</div>
</div>
<div class="profile-card">
  <div class="name">Parent: ${escHtml(parentName)}</div>
  <div class="detail">Family Profile</div>
</div>
${babiesHtml ? `<div class="card"><div class="card-title">The Babies</div>${babiesHtml}</div>` : ''}
<div class="section-title">Newborn Statistics</div>
<div class="stat-grid">
  <div class="stat-box">
    <div class="label">Care</div>
    <div class="row">Total Feedings: ${feedingLogs.length}</div>
    <div class="row">Total Diapers: ${diaperLogs.length}</div>
  </div>
  <div class="stat-box">
    <div class="label">Development</div>
    <div class="row">Milestones: ${milestones.length}</div>
    <div class="row">Tummy Time: ${totalTummyMin.toFixed(0)} min total</div>
  </div>
</div>
${milestoneRows ? `<div class="section-title">Milestone Timeline</div><table><thead><tr><th>Date</th><th>Milestone</th><th>Notes</th></tr></thead><tbody>${milestoneRows}</tbody></table>` : ''}`;

  return wrap("YOUR BABY'S JOURNEY - ARCHIVED BY NESTLY", body);
}
